### ISSUE TITLE
ForwardDiff.jl support?

### ISSUE THREAD

**Issue by longemen3000** [Expander/PolyLog.jl#28]
is it possible to add ForwardDiff.jl support as an extension? i can help if it's necessary

**Comment by Expander** [comment]
That's a good idea! How would that support look like? Would we have to provide additional overloads?

Now that you're asking, I'm wondering if there is a way to also support other differentiation libraries? Do you know if there is a generic way to support all of them?

**Comment by longemen3000** [comment]
For ForwardDiff yes, you would need to support overloads, I can make a PR with the corresponding changes to allow support.
For the rest of AD libraries, I think you only need to support ChainRules (that would be another extension). There is also Enzyme.jl, but Ive never written overloads for that package.

**Comment by Expander** [comment]
A PR would be great! Could you please also add corresponding tests?

One question, though: Would this PR require to add a dependency? I'm asking, because I'd like to avoid this as much as possible. (A "dev"-dependency in the `[extras]` section would be no problem.)

**Comment by longemen3000** [comment]
The extension mechanism does not require direct dependencies (in partícular they are _weak_ dependencies, added in the `[weakdeps]` section). Check this :https://julialang.org/blog/2023/04/julia-1.9-highlights/#package_extensions
